#ifndef LIONHEART_H
#define LIONHEART_H
#include "unit.h"

#include "Player/adc.h"
#include "Player/adi.h"
#include "Player/adn.h"
#include "Player/akf.h"
#include "Player/akf.h"
#include "Player/all.h"
#include "Player/alt.h"
#include "Player/amo.h"
#include "Player/ark.h"
#include "Player/asd.h"
#include "Player/ben.h"
#include "Player/boo.h"
#include "Player/bos.h"
#include "Player/bot.h"
#include "Player/bri.h"
#include "Player/bro.h"
#include "Player/bug.h"
#include "Player/bwc.h"
#include "Player/cal.h"
#include "Player/car.h"
#include "Player/cdg.h"
#include "Player/cjt.h"
#include "Player/ckc.h"
#include "Player/clg.h"
#include "Player/cls.h"
#include "Player/clu.h"
#include "Player/cmd.h"
#include "Player/cow.h"
#include "Player/cra.h"
#include "Player/crb.h"
#include "Player/crd.h"
#include "Player/csq.h"
#include "Player/ctu.h"
#include "Player/cwc.h"
#include "Player/cze.h"
#include "Player/dfv.h"
#include "Player/die.h"
#include "Player/dih.h"
#include "Player/djh.h"
#include "Player/dkb.h"
#include "Player/dkd.h"
#include "Player/dlr.h"
#include "Player/dlt.h"
#include "Player/dnd.h"
#include "Player/dos.h"
#include "Player/drb.h"
#include "Player/drc.h"
#include "Player/dre.h"
#include "Player/dsc.h"
#include "Player/dss.h"
#include "Player/dww.h"
#include "Player/dxv.h"
#include "Player/edb.h"
#include "Player/eds.h"
#include "Player/emj.h"
#include "Player/fed.h"
#include "Player/god.h"
#include "Player/gst.h"
#include "Player/gwh.h"
#include "Player/hlz.h"
#include "Player/hsa.h"
#include "Player/hug.h"
#include "Player/ian.h"
#include "Player/icl.h"
#include "Player/ike.h"
#include "Player/ipm.h"
#include "Player/jaz.h"
#include "Player/jbp.h"
#include "Player/jcl.h"
#include "Player/jdd.h"
#include "Player/jds.h"
#include "Player/jen.h"
#include "Player/jfr.h"
#include "Player/jmf.h"
#include "Player/jmh.h"
#include "Player/jms.h"
#include "Player/jmt.h"
#include "Player/jps.h"
#include "Player/jrp.h"
#include "Player/jrw.h"
#include "Player/jta.h"
#include "Player/jtd.h"
#include "Player/jtg.h"
#include "Player/jwl.h"
#include "Player/kac.h"
#include "Player/kdf.h"
#include "Player/kfc.h"
#include "Player/klb.h"
#include "Player/klh.h"
#include "Player/knk.h"
#include "Player/lam.h"
#include "Player/lav.h"
#include "Player/lel.h"
#include "Player/lhm.h"
#include "Player/lia.h"
#include "Player/lmn.h"
#include "Player/loz.h"
#include "Player/m11.h"
#include "Player/maa.h"
#include "Player/mad.h"
#include "Player/med.h"
#include "Player/mjn.h"
#include "Player/mlg.h"
#include "Player/mlm.h"
#include "Player/mlp.h"
#include "Player/mmh.h"
#include "Player/mos.h"
#include "Player/mpf.h"
#include "Player/mrr.h"
#include "Player/msw.h"
#include "Player/mtc.h"
#include "Player/nac.h"
#include "Player/naw.h"
#include "Player/nva.h"
#include "Player/ork.h"
#include "Player/oss.h"
#include "Player/per.h"
#include "Player/pez.h"
#include "Player/phx.h"
#include "Player/pim.h"
#include "Player/pld.h"
#include "Player/pox.h"
#include "Player/psg.h"
#include "Player/pts.h"
#include "Player/rdt.h"
#include "Player/rgw.h"
#include "Player/rha.h"
#include "Player/roa.h"
#include "Player/rob.h"
#include "Player/rtb.h"
#include "Player/sah.h"
#include "Player/sd9.h"
#include "Player/sdw.h"
#include "Player/sgj.h"
#include "Player/slj.h"
#include "Player/sll.h"
#include "Player/sps.h"
#include "Player/tas.h"
#include "Player/tbb.h"
#include "Player/tcg.h"
#include "Player/tdm.h"
#include "Player/tds.h"
#include "Player/tgf.h"
#include "Player/tgy.h"
#include "Player/the.h"
#include "Player/thl.h"
#include "Player/tlp.h"
#include "Player/tom.h"
#include "Player/tpa.h"
#include "Player/trh.h"
#include "Player/tsm.h"
#include "Player/usa.h"

#include "lionheart2.h"


bool noPlay[NUMTLAS]={
    1,     0,     0,     0,     0,     0,     1,     0,     0,     0,
    1,     1,     0,     0,     0,     1,     0,     0,     0,     0,
    1,     0,     0,     0,     0,     0,     0,     0,     0,     1,
    0,     0,     0,     0,     0,     0,     0,     1,     0,     0,
    0,     0,     1,     0,     0,     0,     1,     0,     0,     0,
    1,     0,     0,     0,     0,     0,     0,     0,     0,     1,
    1,     0,     0,     1,     1,     0,     0,     0,     0,     0,
    0,     1,     0,     0,     0,     0,     0,     0,     1,     0,
    1,     0,     0,     0,     0,     0,     1,     1,     0,     1,
    1,     1,     0,     0,     0,     1,     0,     1,     0,     1,
    0,     0,     1,     0,     1,     0,     0,     0,     0,     0,
    0,     1,     0,     0,     0,     0,     0,     0,     0,     0,
    1,     0,     0,     0,     0,     0,     0,     0,     0,     1,
    0,     0,     0,     0,     0,     1,     0,     1,     0,     0,
    1,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    0,     1,     0,     0,     1,     1,     0,     0,     0,     0,
    0,     1,     1,     0,     0,     1,     1,     0,     0,     0
};
static const std::string tlalist[NUMTLAS+1]={
"adc","adi","adn","akf","akf","all","alt","amo","ark","asd","ben","boo","bos","bot","bri","bro","bug","bwc","cal","car","cdg","cjt","ckc","clg","cls","clu","cmd","cow","cra","crb","crd","csq","ctu","cwc","cze","dfv","die","dih","djh","dkb","dkd","dlr","dlt","dnd","dos","drb","drc","dre","dsc","dss","dww","dxv","edb","eds","emj","fed","god","gst","gwh","hlz","hoe","hsa","hug","ian","icl","ike","ipm","jaz","jbp","jcl","jdd","jds","jen","jfr","jmf","jmh","jms","jmt","jps","jrp","jrw","jta","jtd","jtg","jwl","kac","kdf","kfc","klb","klh","knk","lam","lav","lel","lhm","lia","lmn","loz","m11","maa","mad","med","mjn","mlg","mlm","mlp","mmh","mos","mpf","mrr","msw","mtc","nac","naw","nva","ork","oss","per","pez","phx","pim","pld","pox","psg","pts","rdt","rgw","rha","roa","rob","rtb","sah","sd9","sdw","sgj","slj","sll","sps","tas","tbb","tcg","tdm","tds","tgf","tgy","the","thl","tlp","tom","tpa","trh","tsm","usa",""
};
#endif
